import "./globals.css";
import type { Metadata } from "next";
import { poppins } from "@/app/fonts";
import { PageLayout } from "@/components/PageLayout";
import { OverscrollFillerBottom } from "@/components/OverscrollFillerBottom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <PageLayout>{children}</PageLayout>
        <OverscrollFillerBottom />
      </body>
    </html>
  );
}
